---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp default.html $DEPLOYPATH
    - /bin/cp img $DEPLOYPATH
    - /bin/cp js $DEPLOYPATH
    - /bin/cp css $DEPLOYPATH
    